name: dist/index.js compiler

on: push

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile

      - run: node_modules/.bin/ncc build index.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update dist/index.js"
          file_pattern: dist/index.js

