name: dist/index.js compiler

on: push

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile

      - run: node_modules/.bin/ncc build index.js

      - name: Binary committer
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Version Incrementer"

          git remote add github "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git pull github "${{ github.ref }}" --ff-only

          git add dist/index.js

          if git commit -m "Update dist/index.js"
          then
            git push github "HEAD:${{ github.ref }}"
          fi

