name: dist/index.js compiler

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.1.0
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile

      - run: node_modules/.bin/ncc build index.js

      - uses: ViliusSutkus89/git-auto-commit-action@v4
        with:
          commit_message: "Update dist/index.js"
          file_pattern: dist/index.js

