name: Version Incrementer

on:
  release:
    types: published

jobs:
  versionIncrement:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - run: ./doincrementversion

      - name: git commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Version Incrementer"

          git remote add github "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git pull github "${{ github.ref }}" --ff-only

          git add package.json

          if git commit -m "Post release version increment"
          then
            git push github "HEAD:${{ github.ref }}"
          fi

