name: Version Incrementer

on:
  release:
    types: published

jobs:
  versionIncrement:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - run: ./doincrementversion

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release version increment"
          file_pattern: package.json

