name: Version Incrementer

on:
  release:
    types:
    - published

jobs:
  versionIncrement:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'

      - run: ./doincrementversion

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Post release version increment"
          file_pattern: package.json

