name: Version Incrementer

on:
  release:
    types:
    - published

jobs:
  versionIncrement:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - run: ./doincrementversion

      - uses: ViliusSutkus89/git-auto-commit-action@v4
        with:
          commit_message: "Post release version increment"
          file_pattern: package.json

