name: Release Builder

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: sudo apt-get --quiet install --yes yarn

    - run: yarn install --frozen-lockfile

    - run: node_modules/.bin/ncc build index.js

